### ISSUE TITLE
How to add transaction reference xml block inside request

### ISSUE THREAD

**Issue by chirag7jain** [ptrippett/ups#1]
I want to add this to ShipConfirm Request

```xml
<TransactionReference>
<CustomerContext>guidlikesubstance</CustomerContext>
<XpciVersion>1.0001</XpciVersion>
</TransactionReference>
```

**Comment by ptrippett** [comment]
Sorry I didn't see the issue till now, but I think you already figured it out, You'll need to add the functionality to the gem and send me a pull request.
